export const data =[
    {
        id:'1',
    image :"https://fr.web.img2.acsta.net/pictures/19/02/15/15/32/4373897.jpg",
    rate:2,
    name:"frontier",
    date : "2019",
    description1:"Santiago Gomez has been fighting drug trafficking for years. When one of his informers reveals to him where a drug lord and his millions of dollars is hiding, on the triple border between Paraguay, Brazil and Argentina, he decides to warn his former brothers in arms, struggling to make ends meet, to organize the heist of the century.",
    vedio:'https://www.youtube.com/watch?v=2J5wTsYAh94',
    },
    {id:'2',
        image :"https://imgr.cineserie.com/2018/09/1356320.jpg?imgeng=/f_jpg/cmpr_0/w_2000/h_2667/m_cropbox&ver=1",
        rate: 5,
        name:"dachra",
        date : "2018",
        description1:"Dachra is a Tunisian horror film written and directed by Abdelhamid Bouchnak and released in 2018. It is the first profitable Tunisian film in twenty years, while it has not benefited from subsidies from the Tunisian State, aid from sponsors and Tunisian or foreign funds.", 
        vedio:'https://www.youtube.com/watch?v=a5_WTF7KtYQ',
    },
    {id:'3',
        image :"https://fr.web.img6.acsta.net/pictures/20/10/09/18/05/4227202.jpg",
        rate:4,
        name:"bronx",
        date : "2020",
        description1:"Bronx is a French film written and directed by Olivier Marcha", 
        vedio:'https://www.youtube.com/watch?v=LTt-hVUzSJI',
    },
    {id:'4',
        image :"https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/Halloween_%282018%29_poster.jpg/220px-Halloween_%282018%29_poster.jpg",
        rate:3,
        name:"halloween",
        date : "2018",
        description1:"Laurie Strode is back for a final showdown with Michael Myers, the masked character who has haunted her since she narrowly escaped her murderous madness on Halloween night 40 years earlier.", 
        vedio:'https://www.youtube.com/watch?v=ek1ePFp-nBI',
    }

]